config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'success', action: 'success', controller: 'registrations', as: 'success'

    authenticated :user do
      root 'dashboards#index'
    end

    unauthenticated do
      root 'site#index', as: :unauthenticated_root
    end
  end

  resources :reports do
    get 'export', on: :collection
  end

  resources :timetables

  resources :site, only: :index do
    get 'como-funciona', action: 'how_it_works', as: 'how_it_works', on: :collection
  end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :authenticate_user!

  before_action :initialize_timetable, only: [:index, :create]
  before_action :load_timetable, only: [:edit, :update, :destroy]
  before_action :require_permission, only: [:edit, :update, :destroy]
  before_action :load_timetables

  def create
    @timetable.user = current_user
    if @timetable.update_attributes(timetable_params)
      redirect_to timetables_path, flash: { success: t('flash.reports.create.notice') }
    else
      render 'index'
    end
  end

  def edit
    render 'index'
  end

  def update
    if @timetable.update_attributes(timetable_params)
      redirect_to timetables_path, flash: { success: t('flash.reports.update.notice') }
    else
      render 'index'
    end
  end

  def destroy
    @timetable.destroy
    redirect_to timetables_path, flash: { success: t('flash.reports.destroy.notice') }
  end

  private

  def require_permission
    return unless current_user != @timetable.user
    redirect_to timetables_path
  end

  def initialize_timetable
    @timetable = Timetable.new
  end

  def timetable_params
    params.require(:timetable).permit(:closing_day)
  end

  def load_timetables
    @timetables = current_user.timetables.all.page params[:page]
  end

  def load_timetable
    @timetable = Timetable.find(params[:id])
  end
end

app/views/timetables/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box box-danger">

      <%= simple_form_for @timetable, wrapper: :vertical_form do |f| %>
        <div class="box-body content">

          <%= message(@timetable.errors.messages[:base] || '') %>

          <%= f.input :closing_day, wrapper_html: { class: 'col-xs-5'},
                                    input_html: { class: 'datepicker',
                                                  autocomplete: 'off',
                                                  value: @timetable.closing_day.try(:strftime, "%d/%m/%Y") },
                                    as: :string %>

        </div>
        <div class="box-footer">
          <%= f.button :submit, 'Salvar', class: 'btn-primary', data: { disable: true } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/timetables/_list.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Saldo nos fechamentos</h3>
      </div>
      <div class="box-body table-responsive">
        <div class="dataTables_wrapper form-inline" role="grid">
          <table class="table table-bordered table-hover dataTable">
            <thead>
              <tr>
                <th>Dia do fechamento</th>
                <th>Saldo</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% if @timetables.each do |t|%>
              <tr>
                <td><%= t.closing_day.strftime('%d/%m/%Y') %></td>
                <td>
                  <%= render partial: 'layouts/report_balance', locals: { balance: t.balance } %>
                <td>
                  <%= link_to edit_timetable_path(t), title: 'Editar' do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to timetable_path(t), title: 'Excluir',
                                              data: { confirm: "Você tem certeza?" },
                                              method: :delete do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                </td>
              </tr>
              <% end.empty? %>
                <tr>
                  <td colspan="3">Não há fechamentos</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="box-footer clearfix">
         <%= paginate @timetables %>
      </div>
    </div>
  </div>
</div>

app/views/timetables/index.html.erb
<section class="content-header">
  <h1>Quadro de horas</h1>
</section>
<section class="content">

  <%= render 'form' %>

  <%= render 'list' %>
</section>