config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'success', action: 'success', controller: 'registrations', as: 'success'

    authenticated :user do
      root 'dashboards#index'
    end

    unauthenticated do
      root 'site#index', as: :unauthenticated_root
    end
  end

  resources :reports do
    get 'export', on: :collection
  end

  resources :timetables

  resources :site, only: :index do
    get 'como-funciona', action: 'how_it_works', as: 'how_it_works', on: :collection
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user

  validates :day, :remote, presence: true
  validates :day, uniqueness: { scope: :user_id }
  validate :validate_entry_exit_order

  default_scope { order('day DESC') }

  NEGATIVE = false
  POSITIVE = true

  def worked
    first_total  = time_diff(first_entry, first_exit)
    second_total = time_diff(second_entry, second_exit)
    third_total  = time_diff(third_entry, third_exit)

    first_total + second_total + third_total + timeit(remote).seconds_since_midnight
  end

  def balance
    return { time: worked, sign: POSITIVE } unless working_day

    hours_per_day = Time.parse(user.hours_per_day).seconds_since_midnight
    time, sign = away ?  [hours_per_day, NEGATIVE] : [balance_diff(hours_per_day), positive_balance?(hours_per_day)]

    { time: time, sign: sign }
  end

  def self.find_by_date_range(from, to)
    where('day >= ? AND day <= ?', from, to)
  end

  def self.last_day
    last ? last.day : Date.today
  end

  def entries
    [ first_entry, second_entry, third_entry ]
  end

  def exits
    [ first_exit, second_exit, third_exit ]
  end

  private

  def validate_entry_exit_order
    return if times.compact == times.compact.sort

    errors.add(:base, I18n.t('flash.reports.validations.entry_exit_order'))
  end

  def times
    [
      timeit(first_entry),
      timeit(first_exit),
      timeit(second_entry),
      timeit(second_exit),
      timeit(third_entry),
      timeit(third_exit)
    ]
  end

  def time_diff(entry, exit)
    entry = timeit(entry)
    exit  = timeit(exit)

    if exit && entry
      exit - entry
    else
      0
    end
  end

  def timeit value
    return if value.nil?
    Time.parse(value) unless value.empty?
  end

  def balance_diff hours_per_day
    (worked - hours_per_day).abs
  end

  def positive_balance? hours_per_day
    hours_per_day <= worked
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  before_action :initialize_report, only: [:new, :create]
  before_action :load_report, only: [:edit, :update, :destroy]
  before_action :require_permission, only: [:edit, :update, :destroy]

  def new
    @report.day = Date.today
  end

  def index
    @from = from
    @to = to
    @reports = ReportPresenter.wrap(current_user.reports.find_by_date_range(@from, @to).page params[:page])
  end

  def export
    reports = ReportPresenter.wrap(current_user.reports.find_by_date_range(from, to))
    send_data PdfReport.new(reports, from, to).generate.render,
              filename: "#{current_user.first_name}.pdf",
              type: 'application/pdf',
              disposition: 'inline'
  end

  def create
    @report.user = current_user
    if @report.update_attributes(report_params)
      redirect_to reports_path, flash: { success: t('flash.reports.create.notice') }
    else
      render 'new'
    end
  end

  def update
    if @report.update_attributes(report_params)
      redirect_to reports_path, flash: { success: t('flash.reports.update.notice') }
    else
      render 'edit'
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_path, flash: { success: t('flash.reports.destroy.notice') }
  end

  private

  def from
    param_or_today(:from, 30.days.ago)
  end

  def to
    param_or_today(:to)
  end

  def param_or_today(key, default = Date.today)
    date = params[key]
    date ? Date.parse(date) : default
  rescue ArgumentError
    default
  end

  def require_permission
    return unless current_user != @report.user
    redirect_to reports_path
  end

  def initialize_report
    @report = Report.new
  end

  def load_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(
      :first_entry,
      :first_exit,
      :second_entry,
      :second_exit,
      :third_entry,
      :third_exit,
      :remote,
      :notice,
      :day,
      :away,
      :working_day
    )
  end
end

app/helpers/report_helper.rb
module ReportHelper
  TEXT_COLOR = { true => 'green', false => 'red' }
  ICON = { true => 'plus', false => 'minus' }

  def text_color(status)
    TEXT_COLOR.fetch(status)
  end

  def icon(status)
    ICON.fetch(status)
  end

  def format_time(time)
    hours = time / (60 * 60)
    minutes = (time / 60) % 60
    format('%02d:%02d', hours, minutes)
  end
end

app/views/reports/_export_link.html.erb
<div class="box-tools pull-right">
  <div class="btn-group">
    <button type="button" class="btn btn-warning btn-flat " data-toggle="dropdown">
      <span class="caret"></span>&nbsp; Exportar
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to('PDF', 'javascript:;', data: { url: export_reports_path }, id: 'pdf_export') %></li>
    </ul>
  </div>
</div>

app/views/reports/_form.html.erb
<section class="content-header">
  <h1>Reporte de horas</h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-danger">
        <div class="box-header">
          <h3 class="box-title">Apontamento</h3>
        </div>

        <%= simple_form_for @report, wrapper: :vertical_form do |f| %>
          <div class="box-body content">

            <%= message(@report.errors.messages[:base] || '') %>

            <div class="row col-xs-12">
            <%= f.input :first_entry , wrapper_html: { class: 'col-xs-2 bootstrap-timepicker' },
                                       input_html: { class: 'timepicker' } %>

            <%= f.input :first_exit , wrapper_html: { class: 'col-xs-2 bootstrap-timepicker' },
                                       input_html: { class: 'timepicker' } %>

            <%= f.input :second_entry , wrapper_html: { class: 'col-xs-2 bootstrap-timepicker' },
                                       input_html: { class: 'timepicker' } %>

            <%= f.input :second_exit , wrapper_html: { class: 'col-xs-2 bootstrap-timepicker' },
                                       input_html: { class: 'timepicker' } %>

            <%= f.input :third_entry , wrapper_html: { class: 'col-xs-2 bootstrap-timepicker' },
                                       input_html: { class: 'timepicker' } %>

            <%= f.input :third_exit , wrapper_html: { class: 'col-xs-2 bootstrap-timepicker' },
                                       input_html: { class: 'timepicker' } %>
            </div>

            <%= f.input :remote , wrapper_html: { class: 'col-xs-5 bootstrap-timepicker' },
                                  input_html: { class: 'timepicker' } %>

            <%= f.input :notice, wrapper_html: { class: 'col-xs-10'} %>

            <%= f.input :day, wrapper_html: { class: 'col-xs-4'},
                              input_html: { class: 'datepicker', autocomplete: 'off', value: @report.day.try(:strftime, "%d/%m/%Y")  },
                              as: :string %>

            <%= f.input :away, collection: { 'Sim' => true, 'Não' => false},
                               include_blank: false,
                               wrapper_html: { class: 'col-xs-3'} %>

            <%= f.input :working_day, collection: { 'Sim' => true, 'Não' => false},
                                      include_blank: false,
                                      input_html: { popover: '',
                                                    data: { content: I18n.t('activerecord.attributes.report.working_day_popover'),
                                                            placement: 'top',
                                                            toggle: 'popover' } },
                                      wrapper_html: { class: 'col-xs-3' } %>

          </div>
          <div class="box-footer">
            <%= f.button :submit, 'Salvar', class: 'btn-primary', data: { disable: true } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/reports/_list.html.erb
<div class="box-body table-responsive">
  <div class="dataTables_wrapper form-inline" role="grid">
    <table class="table table-bordered table-hover dataTable">
      <thead>
        <tr>
          <th>Dia</th>
          <th>Primeira Entrada</th>
          <th>Primeira Saída</th>
          <th>Segunda Entrada</th>
          <th>Segunda Saída</th>
          <th>Terceira Entrada</th>
          <th>Terceira Saída</th>
          <th>Remoto</th>
          <th>Total</th>
          <th>Saldo</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @reports.each do |r|%>
        <tr>
          <td><%= r.day.strftime('%d/%m/%Y') %></td>
          <td><%= r.first_entry %></td>
          <td><%= r.estimated_time(:first) %></td>
          <td><%= r.second_entry %></td>
          <td><%= r.estimated_time(:second) %></td>
          <td><%= r.third_entry %></td>
          <td><%= r.estimated_time(:third) %></td>
          <td><%= r.remote %></td>
          <td><%= format_time(r.worked) %></td>
          <td>
            <%= render partial: 'layouts/report_balance', locals: { balance: r.balance } %>
          </td>
          <td>
            <%= link_to edit_report_path(r), title: 'Editar' do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to report_path(r), title: 'Excluir',
                                        data: { confirm: "Você tem certeza?" },
                                        method: :delete do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
            <%= r.info %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="box-footer clearfix">
   <%= paginate @reports %>
</div>

app/views/reports/_search_form.html.erb
<div class="box-tools pull-right">
  <%= simple_form_for :date_range, wrapper: :inline_form,
                                   html: { class: 'form-inline' },
                                   url: reports_path,
                                   method: :get do |f| %>
  <button class="btn btn-default" id="daterange-btn">
      <i class="fa fa-calendar"></i> Datas
      <i class="fa fa-caret-down"></i>
  </button>
  <%= f.input :from, input_html: { name: 'from',
                                   value: @from.strftime('%d/%m/%Y') } %>
  <%= f.input :to, input_html: { name: 'to',
                                 value: @to.strftime('%d/%m/%Y') } %>
  <%= f.button :submit, 'BUSCAR', { class: 'btn btn-primary' } %>
<% end %>
</div>

app/views/reports/edit.html.erb
<%= render 'form' %>

app/views/reports/index.html.erb
<section class="content-header">
  <h1>
    Reporte de horas - Saldo Total
    <span <%= popover('Saldo a partir do último fechamento.') %> >
      <%= render partial: 'layouts/report_balance', locals: { balance: current_user.total_balance } %>
    </span>
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"
              <%= popover("Saldo entre #{@from.strftime('%d/%m/%Y')} e #{@to.strftime('%d/%m/%Y')}. Independente de quadro fechado.")%> >
            Listagem
            <%= render partial: 'layouts/report_balance',
                       locals: { balance: current_user.balance_in_range(@from, @to)} %>
          </h3>
          <%= render 'search_form' %>
          <%= render 'export_link' %>

        </div>
        <%= render 'list' %>
      </div>
    </div>
  </div>
</section>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "reports/index.js" %>
<% end %>

app/views/reports/new.html.erb
<%= render 'form' %>