config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'success', action: 'success', controller: 'registrations', as: 'success'

    authenticated :user do
      root 'dashboards#index'
    end

    unauthenticated do
      root 'site#index', as: :unauthenticated_root
    end
  end

  resources :reports do
    get 'export', on: :collection
  end

  resources :timetables

  resources :site, only: :index do
    get 'como-funciona', action: 'how_it_works', as: 'how_it_works', on: :collection
  end
end

app/views/layouts/_google_analytics.html.erb
<%= analytics_init if Rails.env.production? %>

app/views/layouts/_header.html.erb
<header class="header">
  <%= link_to 'Click', root_path, class: "logo" %>
  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-user"></i>
            <span> <%= current_user.email %> <i class="caret"></i></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to('Profile', edit_user_registration_path, class: 'btn btn-default btn-flat' ) %>
              </div>
              <div class="pull-right">
                <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'btn btn-default btn-flat' ) %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_menu.html.erb
<aside class="left-side sidebar-offcanvas">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left info">
        <p>Olá, <%= current_user.first_name %>!</p>

        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <ul class="sidebar-menu">
      <li>
        <%= link_to root_path do %>
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <% end %>
      </li>
      <li class="treeview active">
        <a href="javascript:;">
          <i class="fa fa-calendar"></i>
          <span>Reporte de Horas</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to reports_path do %>
              <i class="fa fa-angle-double-right"></i> Listagem
            <% end %>
          </li>
          <li>
            <%= link_to new_report_path do %>
              <i class="fa fa-angle-double-right"></i> Novo apontamento
            <% end %>
          </li>
        </ul>
      </li>
      <li class="active">
        <%= link_to timetables_path do %>
          <i class="fa fa-laptop"></i>
          <span>Quadro de horas</span>
        <% end %>
    </li>
    </ul>
  </section>
</aside>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
<div class="content">
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= flash_class(type) %> alert-dismissable">
      <i class="fa <%= flash_icon(type) %>"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= msg %>
    </div>
  <% end %>
</div>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="<%= id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <div class="modal-body">
        <%= render body_partial %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Entendi</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_report_balance.html.erb
<span class="text-<%= local_assigns.fetch(:text_color, text_color(balance[:sign])) %>">
  <i class="fa fa-fw fa-<%= icon(balance[:sign]) %>-circle"></i>
  <%= format_time(balance[:time]) %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Click - <%= current_user.first_name %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/google_analytics' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue">

<%= render 'layouts/header' %>

  <div class="wrapper row-offcanvas row-offcanvas-left">

    <%= render 'layouts/menu' %>
    <aside class="right-side">
      <div style="padding: 60px 20px; background: #f9f2f4; color: #c7254e; text-align: center;">
        <p>
          <i class="fa fa-exclamation-triangle"></i>
          Esse sistema será desligado no dia 28/02/2016 devido a falta de tempo e dinheiro para manutenção. O código desse site é aberto e pode ser encontrado em <a href="https://github.com/brunozrk/click" target="_blank">https://github.com/brunozrk/click</a>. Agradeço pela compreensão.
        </p>
      </div>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </aside>
  </div>
<%= javascript_include_tag 'application' %>
<%= yield :javascript_includes %>
</body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Click - Controle de Horas Online</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Click tem como objetivo oferecer uma ferramenta online para controlar o saldo de horas (banco de horas) de trabalho">
  <%= render 'layouts/google_analytics' %>
  <%= stylesheet_link_tag 'application_site', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div style="font-weight: normal; padding: 100px 20px; background: #f9f2f4; color: #c7254e; text-align: center;">
    <p>
      <i class="fa fa-exclamation-triangle"></i>
      Esse sistema será desligado no dia 28/02/2016 devido a falta de tempo e dinheiro para manutenção. O código desse site é aberto e pode ser encontrado em <a href="https://github.com/brunozrk/click" target="_blank">https://github.com/brunozrk/click</a>. Agradeço pela compreensão.
    </p>
  </div>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Click', site_index_path, class: "navbar-brand" %>
          </div>
          <div class="collapse navbar-collapse" id="navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <%= link_to 'Como funciona?', how_it_works_site_index_path %>
                  </li>
                  <li>
                      <%= link_to 'Registrar', new_user_registration_path %>
                  </li>
                  <li>
                      <%= link_to 'Entrar', user_session_path %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <%= yield %>

  <!-- Footer -->
  <footer>
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <p class="copyright text-muted small">Copyright &copy; ClickHoras 2014</p>
              </div>
          </div>
      </div>
  </footer>
</body>
</html>